-- ============================================
-- ClassShow V4 security/storage upgrade
-- Run this in Supabase SQL Editor before enabling roster/PIN on Render.
-- ============================================

-- Activity-level controls for roster and PIN login.
alter table activities add column if not exists roster_enabled boolean default false;
alter table activities add column if not exists pin_required boolean default false;

-- Teacher-managed student allowlist. PINs are stored as salted HMAC hashes generated by the app.
create table if not exists student_roster (
  id uuid primary key default gen_random_uuid(),
  activity_id uuid references activities(id) on delete cascade not null,
  student_id text not null,
  name text not null,
  class_name text not null,
  group_name text,
  pin_hash text,
  pin_salt text,
  active boolean default true,
  created_at timestamptz default now(),
  updated_at timestamptz default now(),
  unique(activity_id, student_id)
);

-- If student_roster already existed from an old version, ensure required columns exist.
alter table student_roster add column if not exists name text;
alter table student_roster add column if not exists class_name text;
alter table student_roster add column if not exists group_name text;
alter table student_roster add column if not exists pin_hash text;
alter table student_roster add column if not exists pin_salt text;
alter table student_roster add column if not exists active boolean default true;
alter table student_roster add column if not exists created_at timestamptz default now();
alter table student_roster add column if not exists updated_at timestamptz default now();

-- Backfill safe defaults for legacy rows so import/upsert won't fail.
update student_roster set name = coalesce(nullif(trim(name), ''), student_id) where name is null or trim(name) = '';
update student_roster set class_name = coalesce(nullif(trim(class_name), ''), '未分班') where class_name is null or trim(class_name) = '';
update student_roster set active = true where active is null;

-- Remove historical duplicate roster rows before enforcing unique upsert target.
with ranked as (
  select id,
         row_number() over (
           partition by activity_id, student_id
           order by updated_at desc nulls last, created_at desc nulls last, id
         ) as rn
  from student_roster
)
delete from student_roster r
using ranked x
where r.id = x.id and x.rn > 1;

create unique index if not exists student_roster_activity_student_uidx
  on student_roster(activity_id, student_id);

-- Ensure Data API roles can access this new table (important for projects with strict default grants).
grant usage on schema public to anon, authenticated, service_role;
grant select, insert, update, delete on table public.student_roster to anon, authenticated, service_role;

-- The app currently writes roster rows from the Node server through Supabase REST.
-- If Render has no SUPABASE_SERVICE_ROLE_KEY, this uses the anon role, so RLS must not block it.
alter table public.student_roster no force row level security;
alter table public.student_roster disable row level security;

do $$
begin
  if exists (
    select 1
    from pg_policies
    where schemaname = 'public'
      and tablename = 'student_roster'
      and policyname = 'student_roster_server_access'
  ) then
    drop policy student_roster_server_access on public.student_roster;
  end if;
end $$;

create policy student_roster_server_access
  on public.student_roster
  for all
  to anon, authenticated
  using (true)
  with check (true);

-- Track the storage object behind each work so replaced/deleted files can be cleaned up.
alter table submissions add column if not exists storage_path text;
alter table submissions add column if not exists media_type text default 'image';
alter table submissions add column if not exists media_size bigint;

update submissions
set storage_path = substring(image_url from '/storage/v1/object/public/submissions/(.*)$')
where storage_path is null
  and image_url like '%/storage/v1/object/public/submissions/%';

update submissions
set media_type = case
  when lower(coalesce(storage_path, image_url)) ~ '\.(mp4|mov|webm|ogg)(\?|$)' then 'video'
  else 'image'
end
where media_type is null;

-- Remove duplicate ratings before enforcing one rating per student per work.
with ranked as (
  select id,
         row_number() over (
           partition by submission_id, rater_user_id
           order by updated_at desc nulls last, created_at desc nulls last, id
         ) as rn
  from ratings
)
delete from ratings r
using ranked x
where r.id = x.id and x.rn > 1;

create unique index if not exists ratings_submission_rater_uidx
  on ratings(submission_id, rater_user_id);

-- Allow multiple submissions per student per activity.
-- If older deployments created one-row-per-student uniqueness, remove it.
alter table submissions drop constraint if exists submissions_activity_user_uidx;
drop index if exists submissions_activity_user_uidx;

-- One valid view per student per work. Recalculate denormalized view_count afterward.
with ranked as (
  select id,
         row_number() over (
           partition by submission_id, viewer_user_id
           order by viewed_at asc nulls last, id
         ) as rn
  from views
)
delete from views v
using ranked x
where v.id = x.id and x.rn > 1;

create unique index if not exists views_submission_viewer_uidx
  on views(submission_id, viewer_user_id);

update submissions s
set view_count = coalesce(v.cnt, 0)
from (
  select submission_id, count(*)::int as cnt
  from views
  where is_valid = true
  group by submission_id
) v
where s.id = v.submission_id;

update submissions s
set view_count = 0
where not exists (
  select 1 from views v where v.submission_id = s.id and v.is_valid = true
);

-- Likes for display-page feedback suggestions.
create table if not exists activity_feedback_likes (
  id uuid primary key default gen_random_uuid(),
  activity_id uuid references activities(id) on delete cascade not null,
  feedback_id uuid references comments(id) on delete cascade not null,
  user_id uuid references users(id) on delete cascade not null,
  created_at timestamptz default now()
);

with ranked as (
  select id,
         row_number() over (
           partition by feedback_id, user_id
           order by created_at asc nulls last, id
         ) as rn
  from activity_feedback_likes
)
delete from activity_feedback_likes l
using ranked x
where l.id = x.id and x.rn > 1;

create unique index if not exists activity_feedback_likes_feedback_user_uidx
  on activity_feedback_likes(feedback_id, user_id);

create index if not exists activity_feedback_likes_activity_created_idx
  on activity_feedback_likes(activity_id, created_at desc);

grant select, insert, update, delete on table public.activity_feedback_likes to anon, authenticated, service_role;

alter table public.activity_feedback_likes no force row level security;
alter table public.activity_feedback_likes disable row level security;

alter table public.student_roster no force row level security;
alter table public.student_roster disable row level security;
